### PR TITLE
Include Dask 2-D/N-D wrappers for pyFFTW

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/pyFFTW/pyFFTW/issues/175
Requires https://github.com/pyFFTW/pyFFTW/pull/211
Related https://github.com/pyFFTW/pyFFTW/pull/154

Adds 2-D and N-D Dask wrappers of pyFFTW's NumPy interface for use with Dask. Essentially a continuation of the work done to provide 1-D Dask wrappers in PR ( https://github.com/pyFFTW/pyFFTW/pull/154 ). Bumps the Dask minimum version requirement to guarantee these are available.

### CODE REVIEW

**Comment by jakirkham** [comment]
Will require PR ( https://github.com/pyFFTW/pyFFTW/pull/211 ) be merged first. So probably best to hold off review until that is complete.

**Comment by hgomersall** [comment]
I mean #211 .

**Comment by jakirkham** [comment]
They shouldn't conflict as they were built on top of each other. However it makes the diff a bit cleaner and easier to follow if we rebase after each merge.

**Comment by hgomersall** [comment]
It doesn't matter; I'm happy with the just merging.

**Comment by hgomersall** [comment]
Once the tests are complete :)

**Comment by jakirkham** [comment]
Ok, thanks. Merged.

**Pull request merged**
