### PR TITLE
Try to bump against dask 2.8.0

### LINKED ISSUE #276: futurewarnings in dask 2.8 break test suite
please add dask 2.8 compat

seems like only the test suite is affected.

I had to ignore futurewarnings coming from dask, but I guess that's only a temporary solution.

### PR DESCRIPTION
**Pull request by xnox**
Trying to fix #276

### CODE REVIEW

**Comment by hgomersall** [comment]
Do you know why #276 is happening?

**Comment by xnox** [comment]
@hgomersall 
It seems to be caused by dask 2.8.0, see the CI results on this PR that also trigger it (modified to try to use dask 2.8.0 here). I.e. https://travis-ci.org/pyFFTW/pyFFTW/builds/615315904?utm_source=github_status&utm_medium=notification

It does introduce new FutureWarnings that do trip up a few test cases that use `numpy.alltrue` as that is not implemented by dask.
I don't know why `test_shape_and_s_different_lengths` with dask fails.

Also it looks like it is passing with 3.8, but fails under 3.7?

And I failed to make AppVeyor work with 3.8.

**Comment by xnox** [comment]
In Ubuntu, the same test case does fail with python3.8 as seen in https://launchpadlibrarian.net/452580238/buildlog_ubuntu-focal-amd64.pyfftw_0.11.1-3ubuntu1_BUILDING.txt.gz

**Comment by grlee77** [comment]
closing as this PR was superseded by #278

**Pull request closed without merging**
