### PR TITLE
Support FFTW + MPI

### PR DESCRIPTION
**Pull request by fredRos**
This addresses #38

### CODE REVIEW

**Comment by hgomersall** [comment]
There seem to be a lot of things rolled up into this PR - more than just MPI. Certainly, things like separating out the various float length capability is valuable, but I think it should be a separate PR.

It's just too hard at the minute to understand all the potential interactions because I just can't see all the changes easily.

There seem to be some additional wisdom features too (again, no doubt very useful).

Might it be possible to tease apart the various bits of this. In the first instance your enhancements to the core wrappers would be hugely appreciated, and then we can work out what to do about MPI.

Cheers,
Henry

**Comment by hgomersall** [comment]
@fredRos is this any attempt to get this PR merged? I'm still happy to see the code ultimately in, but it needs a bit of work as per the last comment.

**Comment by fredRos** [comment]
I have maintained the branch for the handful of users that I created it for so it is working. In fact I just fixed something yesterday to be compatible with  the latest numpy. But getting this into the main branch is definitely on my large TODO list that says it was due 432 days ago :)

Thanks for pinging me again. I agree a first milestone and separate PR is detecting float lengths. Wisdom stuff is untested so should probably not be included. It's been a long while since my branch diverged so I'm sure there are tons of conflicts. I should have time to work on it in the next weeks. I will get back to asking for suggestions on how you want it

**Comment by hgomersall** [comment]
Great, I look forward to it!

**Comment by hgomersall** [comment]
@fredRos How're things on this branch? Are we getting towards something mergeable?

**Comment by fredRos** [comment]
I think I can close this pull request. Since I have users that rely on this branch, I will not change it. As you suggested above, I have split the pieces. The detection part is in. The second is #189 which is close to completion. After that is merged, I will the MPI bindings in a separate new PR

**Comment by hgomersall** [comment]
Great, thanks!

**Pull request closed without merging**
