### PR TITLE
release notes for 0.11

### PR DESCRIPTION
**Pull request by grlee77**
I have opened an issue for discussion of making a new release at #187

This PR is a draft of release notes summarizing the changes since 0.10.4.  I assumed 0.11 for the release number, but please let me know if you prefer a different number.

### CODE REVIEW

**Comment by hgomersall** [comment]
Nice! I guess we'll keep this a WIP until release.

**Comment by jakirkham** [comment]
Added a PR ( https://github.com/grlee77/pyFFTW/pull/3 ) for some recent updates. Mostly Dask stuff, but tried to get some other things too.

**Comment by grlee77** [comment]
can one of you approve this one so it can be merged?  thanks

**Comment by grlee77** [comment]
Thanks.

**Pull request merged**
