### PR TITLE
Update Dask tests for compatibility with recent Dask

### LINKED ISSUE #276: futurewarnings in dask 2.8 break test suite
please add dask 2.8 compat

seems like only the test suite is affected.

I had to ignore futurewarnings coming from dask, but I guess that's only a temporary solution.

### PR DESCRIPTION
**Pull request by grlee77**
closes #276

Trying this first without bumping dask to 2.x to see if it maintains compatibility with old versions.
Then I can try the dask 2.8 bump as suggested in #277

### CODE REVIEW

**Comment by grlee77** [comment]
ping @jakirkham as the original author of these tests. Do these changes look reasonable to you? (I am not a frequent dask user)

**Comment by jakirkham** [comment]
Yeah this seems fine. Thanks for updating them @grlee77! 😀

**Comment by grlee77** [comment]
Do you want to keep the Travis changes in the same PR. I dropped Python 3.4 to save time because it has reached "end of life" and we probably don't want to keep supporting it going forward.

I should restore SCIPY_WHEELS in one case here before merging so that we still test against upcoming scipy 1.4 for the new `scipy.fft` interfaces.

**Comment by jakirkham** [comment]
Fine by me. Maybe @hgomersall has thoughts?

**Comment by grlee77** [comment]
Actually, looking more closely at the logs, dask is only being tested for Python 2.7 and 3.5. I will have to update the version to a more recent one for a conda package to exist for the newer Python versions

**Comment by hgomersall** [comment]
@jakirkham This all looks fine to me. I don't use Dask, so I'll have to leave the usage issues to you. I'm probably not the best person to review, but I'm happy for it to be merged once people are happy.

**Comment by grlee77** [comment]
@hgomersall or @jakirkham: can one of you merge this, please? It should be good to go.

**Comment by hgomersall** [comment]
@grlee77 You can merge this now...

**Pull request merged**
