### PR TITLE
Support Python 3.12

### PR DESCRIPTION
**Pull request by paugier**
This is basically #370 rebased on master with changes to build wheels for Py 3.12 on Github Actions.

### CODE REVIEW

**Comment by hgomersall** [comment]
These failures look rather odd...

**Comment by paugier** [comment]
The builds are failing only on win_arm64 with

```
File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-3ccuw6go\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 241, in initialize
        assert not self.initialized, "don't init multiple times"
```

I noted that `numpy-1.19.5-cp39-cp39-win_amd64.whl` is used, which does not make sense.

**Comment by paugier** [comment]
It seems that at least numpy, scipy, scikit-learn and scikit-image do not build win_amd64 wheels. It might be reasonable to do the same? What do you think @hgomersall ?

**Comment by paugier** [comment]
> Is this only on python 3.12?

No it's for all supported Python version. I guess it's an issue with the more recent setuptools that is needed for Python 3.12.

I remove win_arm64 from the matrix to follow numpy and scipy. It can be added latter when the community better supports arm64 on Windows.

**Comment by paugier** [comment]
@hgomersall, I thing this PR is ready to be reviewed!

**Review by hgomersall — APPROVED** [review]

**Pull request merged**
