### PR TITLE
add next_fast_len as introduced in scipy 0.18

### LINKED ISSUE #103: scipy_interfaces.fftpack needs _next_regular to support upstream changes
`_next_regular` is designed to support fft implementation specific optimisations. In the case of FFTW, this is different to fftpack, so a custom one should be included (it is used by scipy internal tools).

See https://github.com/scipy/scipy/pull/6124.

### PR DESCRIPTION
**Pull request by grlee77**
closes #103 

This introduces a routine as in `scipy.fftpack` to address the next fast favorable size for FFTs.  Unlike in scipy, FFTW supports additional prime factors.

From the FFTW3 documentation:

>FFTW is best at handling sizes of the form 2^a 3^b 5^c 7^d 11^e 13^f, where e+f is either 0 or 1, and the other exponents are arbitrary. Other sizes are computed by means of a slow, general-purpose algorithm (which nevertheless retains O(n log n) performance even for prime sizes). It is possible to customize FFTW for different array sizes; see Installation and Customization. Transforms whose sizes are powers of 2 are especially fast."

This same text is present in the descriptions for both real and complex FFTs:
http://fftw.org/fftw3_doc/Complex-DFTs.html#Complex-DFTs
http://fftw.org/fftw3_doc/Real_002ddata-DFTs.html#Real_002ddata-DFTs
http://fftw.org/fftw3_doc/Real_002dto_002dReal-Transforms.html#Real_002dto_002dReal-Transforms

I was not sure on the best location for this code.  I have placed it in `builders._utils` for now as its utility is not limited to `scipy.fftpack` wrappers.  I guess the function should also be imported into the `scipy.fftpack` interface namespace as `scipy` users would expect to find it there.

will follow up with a quick performance validation example
also still need to add it to the docs once we settle on the final location

### CODE REVIEW

**Comment by hgomersall** [comment]
This is great, thanks for doing this!

This should be in the same namespace as the equivalent in scipy, so it can drop in seamlessly. In `scipy`, it's in both `scipy.fftpack.helpers` as well as `scipy.fftpack` (to which I assume it is imported).

I think it is sufficient to have it only in `pyfftw.interfaces.scipy_fftpack`, which would mean that you could just include it in `interfaces/scipy_fftpack.py`. The tests can then be put in the equivalent file in `tests`.

**Comment by endolith** [comment]
Yeah it's meant to be used like this https://hgomersall.github.io/pyFFTW/sphinx/tutorial.html#monkey-patching-3rd-party-libraries

https://github.com/scipy/scipy/pull/6124

(Note that variable name "hams" = "Hamming numbers", which yours are not)

**Comment by grlee77** [comment]
> (Note that variable name "hams" = "Hamming numbers", which yours are not)

ahh... I was wondering what "hams" stood for.  can change the variable name here, then.

Related to this, do you feel it is important to test with **very** large integers as was done in the scipy tests?  I have not currently replicated those here (mainly I did not work out what the proper increment would be in the `large size + 1` cases)

>I think it is sufficient to have it only in pyfftw.interfaces.scipy_fftpack, which would mean that you could just include it in interfaces/scipy_fftpack.py. The tests can then be put in the equivalent file in tests.

I understand about having it in the `scipy` interface namespace, but I guess I was thinking that even if one is not using the scipy interface, the `next_fast_len` function will be of use in determining a good transform size.  I can move it where you suggest, but should we also import it at the top level so a user could do:
  `from pyfftw import next_fast_len`?

**Comment by grlee77** [comment]
here is a basic benchmark result validating the current implementation.  (I have used the FFTW builders rather than the scipy interface)

```python
    import time
    import numpy as np
    from matplotlib import pyplot as plt
    from pyfftw.builders import fftn as build_fftn
    from pyfftw.builders._utils import next_fast_len

    all_l = np.arange(2, 1000)
    all_nl = np.zeros_like(all_l)
    all_times = np.zeros(len(all_l))
    all_times_pad = np.zeros(len(all_l))
    time_ratios = np.ones(len(all_l))
    for cnt, l in enumerate(all_l):
        l = int(l)
        print("l = {}".format(l))
        nl = next_fast_len(l)
        all_nl[cnt] = nl
        dl = np.random.randn(l)
        dnl = np.random.randn(nl)

        fft_l = build_fftn(dl, threads=1)
        fft_nl = build_fftn(dnl, threads=1)
        if l < 100:
            nreps = 10000
        elif l < 1000:
            nreps = 1000
        else:
            nreps = 100
        tstart = time.time()
        for n in range(nreps):
            fft_l(dl)
        tl = (time.time() - tstart) / nreps

        if l == nl:
            all_times[cnt] = tl
            all_times_pad[cnt] = tl
            time_ratios[cnt] == 1
            continue

        tstart = time.time()
        for n in range(nreps):
            fft_nl(dnl)
        tnl = (time.time() - tstart) / nreps

        all_times[cnt] = tl
        all_times_pad[cnt] = tnl
        time_ratios[cnt] = all_times_pad[cnt] / all_times[cnt]

    plt.figure(); plt.plot(all_l, 1e3*all_times, all_l, 1e3*all_times_pad)
    plt.legend(['unpadded', 'pad to next fast len'], loc='upper left')
    plt.xlabel('unpadded FFT length')
    plt.ylabel('time (ms)')
```
timings

or in terms of the acceleration factor:
ratios

**Comment by endolith** [comment]
> Related to this, do you feel it is important to test with very large integers as was done in the scipy tests? I have not currently replicated those here (mainly I did not work out what the proper increment would be in the large size + 1 cases)

Probably not?  I went overboard with making sure it didn't miss any corner cases and optimizing for speed.  http://stackoverflow.com/a/19649737/125507  Then again maybe people do super-long FFTs on supercomputers? I don't know.

**Comment by hgomersall** [comment]
Sure, `pyfftw.next_fast_len` works. Adding it to `utils.pxi` means it is exposed to cython as well which is useful. Just use `cpdef` rather than `def`, and add the signature on the first line, and it should work properly (not sure if there is a doc page that needs tweaking too, but it should be easy).

**Comment by grlee77** [comment]
Okay.  I like the `utils.pxi` suggestion better, so I have moved it there.  I now import it from there into the scipy interfaces.  I have rebased/squashed into a single commit to get ride of all the unnecessary history of moving things around.

**Comment by hgomersall** [comment]
Looks good, though I'd like to check it a little more carefully. Does it basically implement the scipy equivalent?

What does napoleon do?

**Comment by grlee77** [comment]
The documentation I had for `next_fast_len` was using numpy style, but I did not realize that the `numpydoc` sphinx extension is not currently a dependency for pyFFTW.  A workaround that avoids adding it as a dependency is to use the  `sphinx.ext.napoleon` extension which does recognize the `Parameters`, `Returns`, and `Examples` fields.  (This extension has been included with sphinx itself by default since version 1.3).

Is this an acceptable solution, or how would you prefer to format the docstring for `next_fast_len`?

**Comment by grlee77** [comment]
without the extension I get the following warnings when building the docs:
```
docstring of pyfftw.next_fast_len:7: SEVERE: Unexpected section title.

Parameters
----------
docstring of pyfftw.next_fast_len:12: SEVERE: Unexpected section title.

Returns
-------
docstring of pyfftw.next_fast_len:17: SEVERE: Unexpected section title.

Examples
--------
```

**Comment by hgomersall** [comment]
Yeah, that's fine. The docs could do with an overhaul to standardise this sort of thing. What does it generate in the output?

**Comment by grlee77** [comment]
Basically, napoleon recognizes both the numpy and google docstring styles.  There is a brief overview here:
https://pypi.python.org/pypi/sphinxcontrib-napoleon

**Comment by grlee77** [comment]
It ends up rendering like this:
screen shot 2017-04-03 at 1 09 12 pm

**Comment by hgomersall** [comment]
It looks good. I think it's how it _ought_ to be across the whole package.

**Comment by hgomersall** [comment]
Is the implementation drawn from the scipy implementation?

**Comment by grlee77** [comment]
Yes.  The core implementation for the inner loops of factors 2, 3 and 5 is exactly copied from scipy.  An additional loop is there for factor 7.  The factor 11 and 13 is handled slightly differently so there is only at most a factor of 11 or 13 but not both as described in the docstring.  There are a couple of cases explictly for this case.

The variable at the top is basically just precomputed results for short transform lengths so that the overhead of computing the factors can be avoided in these cases.  This list was updated to match the pyFFTW factors and is thus longer than the one present in scipy.

**Comment by hgomersall** [comment]
Ok, great. I'll take a look later on, but I suspect it's fine. Thanks!

**Comment by grlee77** [comment]
for reference, the `scipy` implementation is here:

https://github.com/scipy/scipy/blob/ab9eff32ef594a59621404ffe18045fd6bd49e1f/scipy/fftpack/helper.py#L51

**Comment by hgomersall** [comment]
This is great, thanks!

**Pull request merged**
