### PR TITLE
Rename Cache interface tests

### PR DESCRIPTION
**Pull request by jakirkham**
Goes ahead and renames the cache interface test module to match the naming of the other interface test modules.

### CODE REVIEW

**Comment by hgomersall** [comment]
This is a poor solution IMO. We should understand why the problem is occurring.

**Comment by hgomersall** [comment]
I think this is fixed now in the original branch, correct?

**Comment by jakirkham** [comment]
Correct, this is not needed as a workaround. Though it does match the naming of the other interfaces better.

**Comment by hgomersall** [comment]
Hmm, it seems to have merged anyway (I must have missed it in another branch) ;)

**Comment by jakirkham** [comment]
Oh, yeah, it's in the history of PR ( https://github.com/pyFFTW/pyFFTW/pull/154 ), but that PR also reverts this change. So this didn't change anything in the end. Would have rebased it out of the other change, but didn't want to rewrite the branch since you were working on it too. 😉

**Comment by hgomersall** [comment]
It doesn't really matter. I think tbh I like the test name that maps to the module name, which is more like the cache case, but I really don't care that much.

**Pull request merged**
