### PR TITLE
Update NumPy and SciPy interfaces with new norm options (take 2)

### PR DESCRIPTION
**Pull request by grlee77**
This PR resumes #308. There is nothing new here from that PR, I just fixed the conflict with #323 renaming the test folder and dropped most of the unrelated style changes.

The style changes were generally favorable, but were making this harder to review. @hgomersall, if you want to incorporate those, I can add them in a second commit here or we could run some other automated tool on the codebase.

### CODE REVIEW

**Comment by grlee77** [comment]
nice, the GitHub actions for testing are being triggered as expected after #323 was merged. Looks like we still need to disable Appveyor elsewhere, though (attn: @JeppeKlitgaard, @hgomersall)

**Comment by grlee77** [comment]
@hgomersall can you try logging into your Appveyor account and disabling it for this respository? (or maybe it can be disabled in the repository settings here?)

**Comment by grlee77** [comment]
At least some of these test cases will be using NumPy >= 1.20 (required for testing the new norm options). Everything passed with NumPy 1.21 when I tested locally.

**Comment by hgomersall** [comment]
> nice, the GitHub actions for testing are being triggered as expected after #323 was merged. Looks like we still need to disable Appveyor elsewhere, though (attn: @JeppeKlitgaard, @hgomersall)

Though AFAICT no actual tests are being run...

**Comment by hgomersall** [comment]
There doesn't appear to be a step "Run tests" or am I missing something?

**Review by hgomersall — APPROVED** [review]

**Comment by grlee77** [comment]
Most are getting tested as part of the "Build Wheel" section. See here for example: https://github.com/pyFFTW/pyFFTW/runs/4561974445?check_suite_focus=true#step:6:636

(although the testing step is skipped on some architectures where had a known failure as raised in recent issues)

**Comment by hgomersall** [comment]
Gotcha! I approve this merge request.

**Pull request merged**
