### PR TITLE
Update CI release

### PR DESCRIPTION
**Pull request by paugier**

### CODE REVIEW

**Review by hgomersall — APPROVED** [review]

**Comment by hgomersall** [comment]
Looks good to me. Is Versioneer largely redundant now?

**Comment by paugier** [comment]
Warning: this PR should not be merged like that. I commented some lines to see if everything works but I will change that when the CI is done.

**Comment by hgomersall** [comment]
> Warning: this PR should not be merged like that. I commented some lines to see if everything works but I will change that when the CI is done.

Wow, yes. I totally didn't read those lines as commented. My bad!

**Comment by paugier** [comment]
It should be fine now!

**Comment by paugier** [comment]
@hgomersall This one has to be merged before the release. I recall that it is quite simple and only about CI.

**Pull request merged**
