### PR TITLE
 Attempted fix to the problem of the FFTW libs not being downloaded on appveyor.

### PR DESCRIPTION
**Pull request by hgomersall**

### CODE REVIEW

**Comment by hgomersall** [comment]
Ach, it's broken in a new way now. Windows is such a pain in the arse to get right.

**Comment by grlee77** [comment]
Shouldn't Appveyor also run on PRs?  I am not sure where to set that, but it would help identify these problems sooner.

**Comment by hgomersall** [comment]
Yes, it [runs and fails](https://ci.appveyor.com/project/hgomersall/pyfftw/build/job/04djomrrcky13si0). It's not feeding back to github at the moment though.

**Comment by grlee77** [comment]
Looks like we could remove that miniconda install script altogether as it now comes pre-installed on Appveyor:
https://www.appveyor.com/docs/build-environment/#python
http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/

**Comment by hgomersall** [comment]
Great, let's try that...

**Comment by hgomersall** [comment]
That seems to be working now... Thanks!

**Comment by grlee77** [comment]
Great!  Looks good to me

**Comment by hgomersall** [comment]
3.6 is broken. Still I think we can merge with what we have (better than nothing).

**Comment by grlee77** [comment]
see #173 for an attempt at fixing Python 3.6.  The problem appears to be that numpy 1.10 is the oldest version for which there is a conda package for Python 3.6.

**Pull request merged**
