### PR TITLE
R2R try two

### PR DESCRIPTION
**Pull request by drwells**
I spent a few hours rebasing and I am pretty happy with the result. In particular the history is now nice and clean. All of the tests should pass at each commit, so you can review it that way.

I wrote this with the intent of not changing the user-facing API at all (though some details of the `FFTW` class had to change). Therefore this does add some (documented) warts to the library, like those around `_Xfftn`.

### CODE REVIEW

**Comment by drwells** [comment]
The fact that these commits are spread across two years really confuses github...

**Comment by hgomersall** [comment]
This is great work and a really valuable contribution. As it stands though, there are a few things that concern me before merging:

1) The tests are rather sparse. In particular, AFAICT, there are no tests at all for the new builder functions. The tests you have included test the functionality of the new code but very little in the way of testing failure modes and edge cases. I appreciate this is a huge pain to do completely, but the effort on the existing code base has proved to yield a very robust almost bug-free library (I think there is one proper bug in the issue list at the moment). My strategy would have been to re-purpose as much of the existing testing infrastructure as possible (this is how all the other transforms are tested, and I don't think r2r is so radically different) - the classes were designed very much with that in mind. Also, those tests should be manually validated as failing when the functionality is removed.

As an aside, I've actually picked up more than one bug in FFTW itself through the thorough testing.

2) I think we really need to move across to the API discussed in #39 - specifically, deprecate the `direction` parameter and use a `transform_type` argument with suitable enumerations. `direction` is IMO a confusing misnomer when it comes to r2r (and has been for a long time anyway). This would improve `_Xfftn` as well.

3) The interfaces bit should be complete before merging, and as close as possible to `scipy.fftpack`. `scipy.fftpack.dct(a, type=1, norm='ortho')` fails with `NotImplementedError`, but `pyfftw.interfaces.scipy_fftpack.dct(a, type=1, norm='ortho')` will quietly ignore the norm flag. This should also be acknowledged in the test suite.

Similarly, the `n` parameter not `None` raises. Can the existing `_FFTWWrapper` not be modified quite easily? (it just wraps the `FFTW` object with suitable slicers).

4) The documentation needs updating.

As I said, this is valuable work so I sincerely encourage you to persist with this! Thanks!

**Comment by drwells** [comment]
Thank you for the careful review. I agree on all points. It will take me some time to get through this but I will put the time into it (as opposed to the two year gap between now and when #39 was opened).

As far as API changes go: this is your project and I will conform to whatever view you have about the future of the `direction` parameter. I think the best way to handle that would be to add a small, separate change to the library where we make `direction` a deprecated alias of `transform_type` and then I will rebase this branch against that.

Is `_Xfftn` purely internal? If so I will probably change its argument list, unless the aforementioned `transform_type` change beats me to it.

Regardless, here is a TODO list for this branch:
- [ ] Tests for builder functions
- [ ] Finish the `scipy` interface (I foolishly thought I had finished this in 2014 and did not check back)
- [ ] Improve `_Xfftn`
- [ ] Update documentation to describe real to real features

**Comment by hgomersall** [comment]
Yes, I concur with this. The tweak to the API can be made quite easily. It's enough for the time being for you I think to just add the extra parameter (ignoring the deprecation issue). At some point soon I'll make sure everything is consistent and add suitable deprecation warnings and policy for conflicting args as such like.

It's not *my* project as such, I depend on consensus, so feel free to dissent. :)

**Comment by hgomersall** [comment]
Apologies, I just ticked your todo list -  I wasn't aware of that feature! (and I don't know what state it was in because the page hadn't updated).

**Comment by drwells** [comment]
You done broked it!

**Comment by drwells** [comment]
I have not really looked at this in almost a year: I have been working on completely unrelated projects and this has not been a priority for me.

ping @crowsonkb @jo1763 @d-mueller: the three of you are interested in this work. Would you be willing to write the missing tests (e.g., tests for the builder functions and tests for the failure modes)? I believe these are the main blocks from this getting merged (we can raise `NotImplementedError`s for padding and truncation, though it would be nice to have those). Thoughts?

**Comment by hgomersall** [comment]
*poke* still general enthusiasm for merging this work if we can deal with the outstanding blockers.

**Comment by drwells** [comment]
You're right; this has been open too long. I'll wrap this up in January when I can sit down for a few days and get caught up on other changes made to this library.

**Comment by hgomersall** [comment]
Great! There are a few changes that are finding their way in that might influence this. Specifically the work on supporting different sets of precision.

**Comment by drwells** [comment]
I don't see any open PRs or issues on supporting different precision sets; where is this being discussed?

also:
> 
> Conflicting files
> pyfftw/builders/_utils.py
> pyfftw/builders/builders.py
> pyfftw/interfaces/_utils.py
> pyfftw/interfaces/scipy_fftpack.py
> pyfftw/pyfftw.pyx
> sphinx/tutorial.rst
> test/test_pyfftw_scipy_interface.py

*shudders*

**Comment by hgomersall** [comment]
Oops, sorry. Thinks like #189 and #185.

**Comment by drwells** [comment]
Thats right; the shared object files have different names for different precisions. Its been awhile.

**Comment by hgomersall** [comment]
Closing in light of #256 being approved. Thanks @drwells

**Pull request closed without merging**
