### PR TITLE
Possible fix of issue #346

### PR DESCRIPTION
**Pull request by AlexeyBarsuk**

### CODE REVIEW

**Comment by hgomersall** [comment]
This seems like a good and simple solution. Does it solve your requirements?

**Comment by AlexeyBarsuk** [comment]
It looks it does. I was not able to reproduce crush (#346) and I get expected results when using cache with multiple threads ( #376)

**Comment by hgomersall** [comment]
Hmmm, tests are failing...

**Comment by AlexeyBarsuk** [comment]
Can't imagine how changes from my commits can break tests.  Commit with lock on plan destruction should not influence any way to results of FFT routines. Moreover the lock should be there.
As about the second commit - there are assertions in tests that do not use cache at all. For example 
```
   /project/tests/test_pyfftw_scipy_fft.py:194: AssertionError
  ____________ InterfacesScipyR2RFFTNTestDSTNFloat64.test_normalized _____________
```
 So this commit does not influence to these tests.
 
From the other side I see that scipy version installed for tests is the newest. 
```
 Collecting scipy
    Downloading scipy-1.13.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
```
Maybe it is too brave assumption, but in case of non fixed versions of external libraries in tests, the problems with tests may be related to new versions of external libraries. Any way I do not have any reasonable assumption why tests are failed.

**Comment by hgomersall** [comment]
I don't think its your changes, I just think the tests are broken, which is a problem in its own right.

**Comment by paugier** [comment]
I think this just needs to be rebased. For simplicity, I'm going to do it in a new PR.

**Comment by hgomersall** [comment]
Changes merged into #381

**Pull request closed without merging**
